### ISSUE TITLE
Bug: Password Reset form not loading from gmail link

### ISSUE THREAD

**Issue by raimahima22** [SumitNepal10/VROOM-Car-Rental-Service#10]
**Steps to Reproduce**
- Click on the forgot password link in the login page.
- Go to your email and click on the password reset form link.

**The current behavior**
The password reset form does not load from the link in the mail.

**The expected behavior**
Clicking the link in the password reset email should open a functional password reset form.

**Comment by SumitNepal10** [comment]
fixed
