### ISSUE TITLE
Bug: Deleting of Car from admin dashboard not working

### ISSUE THREAD

**Issue by raimahima22** [SumitNepal10/VROOM-Car-Rental-Service#18]
Steps to Reproduce:

- Log in to the admin dashboard with appropriate credentials.
- Navigate to the section for managing cars.
- Select a car entry to delete.
- Click on the delete button.
- Observe that the car entry is not removed from the system, and the deletion process does not complete successfully.

Expected Behavior:
Upon initiating the deletion process from the admin dashboard, the selected car entry should be permanently removed from the system's database.

Actual Behavior:
Despite following the deletion procedure in the admin dashboard, car entries persist in the database, indicating that the deletion process is not executing as intended.

**Comment by Susan-Nepal** [comment]
bug fixed
