### ISSUE TITLE
Bug: Nav Bar Color Indicator Not Updating on Page Change

### ISSUE THREAD

**Issue by raimahima22** [SumitNepal10/VROOM-Car-Rental-Service#22]
**Steps to reproduce :**
1. Navigate to any page within the website.
2. Observe the color indicator in the navigation bar, indicating the current page.
3. Click on a link to navigate to another page.
4. Note that the color indicator does not change to reflect the new current page.

**Expected Behavior:**
The color indicator in the navigation bar should dynamically update to highlight the current page or section being viewed, providing clear navigation feedback to the user.
**Current Behavior**
The color indicator in the navigation bar does not update to highlight the current page.

**Comment by rewant-the-thapa** [comment]
The color indicator in the navigation bar now dynamically update to highlight the current page or section being viewed, providing clear navigation feedback to the user.
