### ISSUE TITLE
Bug: Unresolved Variables 'isAdmin' and 'currentPath' causing 'no-undef' Error"

### ISSUE THREAD

**Issue by raimahima22** [SumitNepal10/VROOM-Car-Rental-Service#31]
**Steps to Reproduce:**
-Navigate to the file containing the reported issue.
-Inspect line 30, column 19, and line 46, column 7, where 'isAdmin' and 'currentPath' are referenced respectively.
-Attempt to execute the code or conduct static analysis to observe the 'no-undef' error.
**Expected Behavior:**
All variables used within the codebase should be properly defined within their respective scopes to prevent 'no-undef' errors.
**Actual Behavior:**
Unresolved variable is causing no-undef error
![unnamed](https://github.com/SumitNepal10/VROOM-Car-Rental-Service/assets/127717820/34db4717-0866-485b-8293-e7541405989f)

**Comment by SumitNepal10** [comment]
bug fixed
